#Configuración de la aplicación Spring Boot para conectarse a una base de datos PostgreSQL.
spring.application.name=ApiPoyecto
spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto
spring.datasource.username=postgres
spring.datasource.password=oretania

# Configuración de JPA/Hibernate para PostgreSQL.
# La propiedad 'spring.jpa.hibernate.ddl-auto=update' permite que Hibernate actualice
# automáticamente el esquema de la base de datos según las entidades definidas en el código.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
